import Vue from 'vue'
import Vuex from 'vuex'
import actions from './actions'
import mutations from './mutations'
import getters from './getters'

Vue.use(Vuex)

export function createStore() {
  return new Vuex.Store({
    state: {
      lists: {},
      Mvlist: {},
      singers: [],
      currentPlay: {},
      isplaying: false,
      ispausing: true,
      Radios: [
        {
        "disstid": "4104519030",
        "coveradurl": "",
        "dissid": 4104519,
        "login": "on**",
        "uin": "oi-iNKC5NKnl7v**",
        "encrypt_uin": "oi-iNKC5NKnl7v**",
        "owndir": 0,
        "dissname": "2018上半年粤语新歌 Top 50",
        "logo": "http://p.qpic.cn/music_cover/gaSSCRswoq7NlpHA8vK1PqGr6rCVbibywnzz7QlyacA39gBrDyDJia8A/300?n=1",
        "pic_mid": "",
        "album_pic_mid": "",
        "pic_dpi": 300,
        "isAd": 0,
        "desc": "转眼2018年已经过了一半，不少新生代歌手也在上半年发了自己的新歌<br>由编辑为你精选的2018年上半年发行、同时也是根据站内播放排行的新歌&#160;Top&#160;50<br>除了经典的粤语歌，我们更应该关注粤语歌坛这些新生代带给我们的新作品<br>希望你们会喜欢。",
        "ctime": 1527040399,
        "mtime": 0,
        "headurl": "http://thirdqq.qlogo.cn/g?b=sdk&k=jkVSicXlX69s5fR14UibicZzg&s=140&t=1483432682",
        "ifpicurl": "",
        "nick": "歌单狂魔",
        "nickname": "歌单狂魔",
        "type": 0,
        "singerid": 0,
        "singermid": "",
        "isvip": 0,
        "isdj": 0,
        "tags": [{
            "id": 166,
            "name": "粤语",
            "pid": 166
          },
          {
            "id": 6,
            "name": "流行",
            "pid": 6
          }
        ],
        "songnum": 50,
        "songids": "213682129,213777375,213334870,213535879,212783750,212870983,213390730,213729090,213193131,213134188,213677797,213424111,213051242,212843588,212831900,213479032,213432268,212767289,213187703,213804162,213207076,213682073,212671682,212785078,212805244,213386809,213187628,213228617,213356207,213002409,213369900,212869239,104176598,213195707,213213670,213323186,213353732,213334168,213360498,213917220,213048993,212808512,213103005,202982655,213264993,213076000,213524983,213428823,213334930,213681410",
        "songtypes": "13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13",
        "total_song_num": 50,
        "song_begin": 0,
        "cur_song_num": 50,
        "songlist": [{
            "albumdesc": "",
            "albumid": 4003856,
            "albummid": "001IzNZy3cz9vP",
            "albumname": "男人背后",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 254,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 12132,
              "mid": "00180Rk61RE4qh",
              "name": "周柏豪"
            }],
            "size128": 4073628,
            "size320": 10183599,
            "size5_1": 0,
            "sizeape": 51744363,
            "sizeflac": 52012844,
            "sizeogg": 5779525,
            "songid": 213682129,
            "songmid": "003cZo6332umkR",
            "songname": "男人背后",
            "songorig": "男人背后",
            "songtype": 0,
            "strMediaMid": "003cZo6332umkR",
            "stream": 6,
            "switch": 636675,
            "type": 0,
            "vid": "a0026nvv3r4"
          },
          {
            "albumdesc": "",
            "albumid": 4022988,
            "albummid": "002VDWOE48VNWu",
            "albumname": "单身狗",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 237,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 235,
              "mid": "003nS2v740Lxcw",
              "name": "李克勤"
            }],
            "size128": 3798189,
            "size320": 9495103,
            "size5_1": 0,
            "sizeape": 44566597,
            "sizeflac": 44641320,
            "sizeogg": 5178829,
            "songid": 213777375,
            "songmid": "0027kWqH3dzqe5",
            "songname": "单身狗",
            "songorig": "单身狗",
            "songtype": 0,
            "strMediaMid": "003ll1je3oSBaV",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3954981,
            "albummid": "001ElPoh3ezSru",
            "albumname": "子华说",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 292,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
                "id": 3347,
                "mid": "000NFT2p1GbnPB",
                "name": "古巨基"
              },
              {
                "id": 4901,
                "mid": "000toTh01nL7dm",
                "name": "黄子华"
              }
            ],
            "size128": 4684680,
            "size320": 11711139,
            "size5_1": 0,
            "sizeape": 56227737,
            "sizeflac": 56366526,
            "sizeogg": 6770598,
            "songid": 213334870,
            "songmid": "0048hQi72c7HN9",
            "songname": "子华说",
            "songorig": "子华说",
            "songtype": 0,
            "strMediaMid": "001cMrT60hcOkk",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "j0026aay41c"
          },
          {
            "albumdesc": "《飞虎之潜行极战》网络剧片尾曲",
            "albumid": 3984969,
            "albummid": "000nj9IH4bnySJ",
            "albumname": "虽然...这个世界",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 234,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
                "id": 14579,
                "mid": "001LeFO32Qf388",
                "name": "黄宗泽"
              },
              {
                "id": 4798,
                "mid": "001ktLDD1D1tHp",
                "name": "吴卓羲"
              }
            ],
            "size128": 3755581,
            "size320": 9388166,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5131455,
            "songid": 213535879,
            "songmid": "002iPCnT1gyFpE",
            "songname": "虽然...这个世界",
            "songorig": "虽然...这个世界",
            "songtype": 0,
            "strMediaMid": "002iPCnT1gyFpE",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3884877,
            "albummid": "0018vPMO3MYrsE",
            "albumname": "Luna",
            "alertid": 23,
            "belongCD": 4,
            "cdIdx": 0,
            "interval": 301,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 158520,
              "mid": "002XVZaw3X63Kp",
              "name": "AGA"
            }],
            "size128": 4823857,
            "size320": 12059357,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 6764155,
            "songid": 212783750,
            "songmid": "0025wbSo0dtSrE",
            "songname": "无期",
            "songorig": "无期",
            "songtype": 0,
            "strMediaMid": "0029Omxk2hOYbZ",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "m0025tfp05w"
          },
          {
            "albumdesc": "",
            "albumid": 3882298,
            "albummid": "000BMVBb3qlmKd",
            "albumname": "一二三，三二一",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 327,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 171,
              "mid": "000xogLP35ayzS",
              "name": "杨千嬅"
            }],
            "size128": 5247687,
            "size320": 13118820,
            "size5_1": 0,
            "sizeape": 36623169,
            "sizeflac": 36861918,
            "sizeogg": 7289403,
            "songid": 212870983,
            "songmid": "000UqzrF30jP50",
            "songname": "一二三，三二一",
            "songorig": "一二三，三二一",
            "songtype": 0,
            "strMediaMid": "001Hg9Y03DH1vE",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "第三十七届香港电影金像奖原创主题歌曲",
            "albumid": 3964604,
            "albummid": "004bXrwj0xO19m",
            "albumname": "不死",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 140,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
                "id": 6507,
                "mid": "000SCb5M3aMP6Z",
                "name": "张继聪"
              },
              {
                "id": 4856,
                "mid": "000N3nfJ398H07",
                "name": "蔡卓妍"
              }
            ],
            "size128": 2255497,
            "size320": 5638459,
            "size5_1": 0,
            "sizeape": 17177503,
            "sizeflac": 17230365,
            "sizeogg": 3407141,
            "songid": 213390730,
            "songmid": "000hXgm43sTGhg",
            "songname": "不死",
            "songorig": "不死",
            "songtype": 0,
            "strMediaMid": "0036qaD83KQgIV",
            "stream": 0,
            "switch": 606007,
            "type": 0,
            "vid": "c0026mkjlxi"
          },
          {
            "albumdesc": "",
            "albumid": 4015164,
            "albummid": "001tAJgq19ofa5",
            "albumname": "流着泪说分手",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 251,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 945860,
              "mid": "002Rotz61Mrf20",
              "name": "阿细"
            }],
            "size128": 4018045,
            "size320": 10044808,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5482500,
            "songid": 213729090,
            "songmid": "000ihtLM2tl4HX",
            "songname": "流着泪说分手",
            "songorig": "流着泪说分手",
            "songtype": 0,
            "strMediaMid": "000ihtLM2tl4HX",
            "stream": 4,
            "switch": 81719,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3931514,
            "albummid": "003CA86C0tbiyq",
            "albumname": "尾站天国",
            "alertid": 23,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 249,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 173,
              "mid": "000ynT3J1Hrdp1",
              "name": "陈慧琳"
            }],
            "size128": 3996723,
            "size320": 9991293,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5665413,
            "songid": 213193131,
            "songmid": "001pEtGF1k8j9h",
            "songname": "尾站天国",
            "songorig": "尾站天国",
            "songtype": 0,
            "strMediaMid": "003luRfj2Mh9zN",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "s0025p396zf"
          },
          {
            "albumdesc": "",
            "albumid": 3920911,
            "albummid": "0038Ypu830calx",
            "albumname": "演员的自我修养",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 281,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 26406,
              "mid": "00367xza48QUVv",
              "name": "许廷铿"
            }],
            "size128": 4511243,
            "size320": 11277793,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 6475922,
            "songid": 213134188,
            "songmid": "0021seZj3UPUQa",
            "songname": "演员的自我修养",
            "songorig": "演员的自我修养",
            "songtype": 0,
            "strMediaMid": "004Q0ZB92BUTQz",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "f0026mksrxg"
          },
          {
            "albumdesc": "《栋仁的时光》电视剧片尾曲",
            "albumid": 4002345,
            "albummid": "001elk8j4IF9wf",
            "albumname": "回到以前",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 216,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1165170,
              "mid": "004TZBsj4dQmjX",
              "name": "HANA"
            }],
            "size128": 3457976,
            "size320": 8644641,
            "size5_1": 0,
            "sizeape": 24396870,
            "sizeflac": 24498641,
            "sizeogg": 5005611,
            "songid": 213677797,
            "songmid": "000xQrFp33bCK7",
            "songname": "回到以前",
            "songorig": "回到以前",
            "songtype": 0,
            "strMediaMid": "003O6GoR1wBhC6",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "z00262gvgu6"
          },
          {
            "albumdesc": "",
            "albumid": 3969564,
            "albummid": "0027eiwT3oIe7m",
            "albumname": "生涯规划",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 287,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 5021,
              "mid": "0018IojC2R0SZW",
              "name": "卫兰"
            }],
            "size128": 4599000,
            "size320": 11497208,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 6120265,
            "songid": 213424111,
            "songmid": "001w9RVG2iHoOO",
            "songname": "生涯规划",
            "songorig": "生涯规划",
            "songtype": 0,
            "strMediaMid": "001kgrlQ2J3idd",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "x00267xj0ii"
          },
          {
            "albumdesc": "",
            "albumid": 3908044,
            "albummid": "001Amco42ms4E6",
            "albumname": "忍",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 248,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 25685,
              "mid": "003F2pV84VWikP",
              "name": "林欣彤"
            }],
            "size128": 3979575,
            "size320": 9948659,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5746279,
            "songid": 213051242,
            "songmid": "003jlsXh2KETOW",
            "songname": "忍",
            "songorig": "忍",
            "songtype": 0,
            "strMediaMid": "003jlsXh2KETOW",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": "t0025a3yhjm"
          },
          {
            "albumdesc": "",
            "albumid": 3877240,
            "albummid": "003FAj5o2tdAr6",
            "albumname": "维多利亚",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 227,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 3614,
              "mid": "0001lZdB0X5klv",
              "name": "JW"
            }],
            "size128": 3647725,
            "size320": 9118999,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 4875447,
            "songid": 212843588,
            "songmid": "004JgDqX2ZpLBM",
            "songname": "维多利亚",
            "songorig": "维多利亚",
            "songtype": 0,
            "strMediaMid": "004JgDqX2ZpLBM",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": "e00257e3cux"
          },
          {
            "albumdesc": "《平安谷之诡谷传说》电视剧主题曲",
            "albumid": 3875533,
            "albummid": "00065Ns6010c5c",
            "albumname": "半边天",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 210,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 6346,
              "mid": "000qCCvH1SpYQ3",
              "name": "胡琳"
            }],
            "size128": 3372286,
            "size320": 8430428,
            "size5_1": 0,
            "sizeape": 21167248,
            "sizeflac": 21281894,
            "sizeogg": 4660494,
            "songid": 212831900,
            "songmid": "002Jb4Aj2TzyLF",
            "songname": "半边天",
            "songorig": "半边天",
            "songtype": 0,
            "strMediaMid": "002Jb4Aj2TzyLF",
            "stream": 3,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3977877,
            "albummid": "003AbSH936aWIk",
            "albumname": "dal segno",
            "alertid": 100002,
            "belongCD": 7,
            "cdIdx": 0,
            "interval": 303,
            "isonly": 0,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 4525,
              "mid": "0047oo0F4LOsvh",
              "name": "Supper Moment"
            }],
            "size128": 4861511,
            "size320": 12153436,
            "size5_1": 0,
            "sizeape": 34422228,
            "sizeflac": 34567403,
            "sizeogg": 7015933,
            "songid": 213479032,
            "songmid": "004854OB2NhRQT",
            "songname": "橙海",
            "songorig": "橙海",
            "songtype": 0,
            "strMediaMid": "001S8LOg2dUx0J",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "y0026dzyfzm"
          },
          {
            "albumdesc": "",
            "albumid": 3970771,
            "albummid": "004NnwMa1UWc66",
            "albumname": "信",
            "alertid": 23,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 286,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 3860,
              "mid": "001qDxJb18rQ8c",
              "name": "李幸倪"
            }],
            "size128": 4590221,
            "size320": 11475263,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5828206,
            "songid": 213432268,
            "songmid": "004FGD5t0fBrJD",
            "songname": "信",
            "songorig": "信",
            "songtype": 0,
            "strMediaMid": "004FGD5t0fBrJD",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "e0026arty0b"
          },
          {
            "albumdesc": "",
            "albumid": 3864246,
            "albummid": "003fGUvu3r4U6N",
            "albumname": "饥饿游戏",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 228,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 5042,
              "mid": "002Y8oJ20bheep",
              "name": "关楚耀"
            }],
            "size128": 3661102,
            "size320": 9152459,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5154130,
            "songid": 212767289,
            "songmid": "000BadXZ14hyTY",
            "songname": "饥饿游戏",
            "songorig": "饥饿游戏",
            "songtype": 0,
            "strMediaMid": "000BadXZ14hyTY",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3930711,
            "albummid": "003khQp83cgY6d",
            "albumname": "嫁给我",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 261,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 919,
              "mid": "000HXbCA0TBIfB",
              "name": "罗力威"
            }],
            "size128": 4185669,
            "size320": 10463834,
            "size5_1": 0,
            "sizeape": 54451851,
            "sizeflac": 54450013,
            "sizeogg": 5973691,
            "songid": 213187703,
            "songmid": "004DbhZ345FABD",
            "songname": "嫁给我",
            "songorig": "嫁给我",
            "songtype": 0,
            "strMediaMid": "004DbhZ345FABD",
            "stream": 1,
            "switch": 636675,
            "type": 0,
            "vid": "p0025csz5xg"
          },
          {
            "albumdesc": "",
            "albumid": 4027123,
            "albummid": "004EpbZM43fGgt",
            "albumname": "骑膊马",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 270,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 6378,
              "mid": "002mbmmr4LL8Ef",
              "name": "泳儿"
            }],
            "size128": 4336100,
            "size320": 10839963,
            "size5_1": 0,
            "sizeape": 49279318,
            "sizeflac": 49325703,
            "sizeogg": 5767912,
            "songid": 213804162,
            "songmid": "001iyA8a0vBrN8",
            "songname": "骑膊马",
            "songorig": "骑膊马",
            "songtype": 0,
            "strMediaMid": "001IJ1pg0bJkeZ",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "i0026n4m2aa"
          },
          {
            "albumdesc": "",
            "albumid": 3934476,
            "albummid": "003y3FQC2xGo1w",
            "albumname": "凯旋门",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 250,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 184290,
              "mid": "0022MM7z3vPjwm",
              "name": "吴业坤"
            }],
            "size128": 4012184,
            "size320": 10030169,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5605776,
            "songid": 213207076,
            "songmid": "00101J3m2xSc5A",
            "songname": "凯旋门",
            "songorig": "凯旋门",
            "songtype": 0,
            "strMediaMid": "00101J3m2xSc5A",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": "l00265uiz72"
          },
          {
            "albumdesc": "《栋仁的时光》电视剧主题曲",
            "albumid": 4003827,
            "albummid": "003c8wf41gxmtI",
            "albumname": "最难忘一天",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 247,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 28688,
              "mid": "003PDwti3g1aa3",
              "name": "胡鸿钧"
            }],
            "size128": 3958279,
            "size320": 9894570,
            "size5_1": 0,
            "sizeape": 24551055,
            "sizeflac": 24631858,
            "sizeogg": 5153437,
            "songid": 213682073,
            "songmid": "0045CjFj4b95i7",
            "songname": "最难忘一天",
            "songorig": "最难忘一天",
            "songtype": 0,
            "strMediaMid": "0045CjFj4b95i7",
            "stream": 7,
            "switch": 636675,
            "type": 0,
            "vid": "s0026z0b6eq"
          },
          {
            "albumdesc": "",
            "albumid": 3849744,
            "albummid": "001FlxOw4Uok5f",
            "albumname": "有火",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 234,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 146,
              "mid": "004GPm8B362txY",
              "name": "谢霆锋"
            }],
            "size128": 3745940,
            "size320": 9364565,
            "size5_1": 0,
            "sizeape": 53848403,
            "sizeflac": 53806444,
            "sizeogg": 5361220,
            "songid": 212671682,
            "songmid": "0044R0mB0mgMNy",
            "songname": "有火",
            "songorig": "有火",
            "songtype": 0,
            "strMediaMid": "003TULQS0NSLE8",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "b0025wzxdtu"
          },
          {
            "albumdesc": "黑白灰三部曲之黑",
            "albumid": 3887714,
            "albummid": "001uZvk73PKvrb",
            "albumname": "黑白彩虹",
            "alertid": 100002,
            "belongCD": 4,
            "cdIdx": 0,
            "interval": 283,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1056006,
              "mid": "001Ntj9n32DZ7u",
              "name": "陈明憙Jocelyn"
            }],
            "size128": 4543860,
            "size320": 11359049,
            "size5_1": 0,
            "sizeape": 32207373,
            "sizeflac": 32133756,
            "sizeogg": 6247433,
            "songid": 212785078,
            "songmid": "003N4PxU1QPtmq",
            "songname": "影子",
            "songorig": "影子",
            "songtype": 0,
            "strMediaMid": "0017rqzU1WDiKU",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "b0025d3qnbx"
          },
          {
            "albumdesc": "",
            "albumid": 3870644,
            "albummid": "0036wbvT47p6oB",
            "albumname": "和好",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 274,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 202189,
              "mid": "004Dwn2p1doLF9",
              "name": "邓小巧"
            }],
            "size128": 4397120,
            "size320": 10992516,
            "size5_1": 0,
            "sizeape": 29115003,
            "sizeflac": 29325523,
            "sizeogg": 6034695,
            "songid": 212805244,
            "songmid": "001fMNKF4Br3GA",
            "songname": "和好",
            "songorig": "和好",
            "songtype": 0,
            "strMediaMid": "003op0gG12POmJ",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "w0026xx4ywe"
          },
          {
            "albumdesc": "",
            "albumid": 3963795,
            "albummid": "004eZbM52rvhze",
            "albumname": "Yeah",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 178,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 19883,
              "mid": "002igtyj493x32",
              "name": "林二汶"
            }],
            "size128": 2863636,
            "size320": 7158794,
            "size5_1": 0,
            "sizeape": 22678579,
            "sizeflac": 22639521,
            "sizeogg": 4364199,
            "songid": 213386809,
            "songmid": "001MmE903I0Gto",
            "songname": "Yeah",
            "songorig": "Yeah",
            "songtype": 0,
            "strMediaMid": "001J6bhu2mdFmd",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "n0026ikr20p"
          },
          {
            "albumdesc": "",
            "albumid": 3930695,
            "albummid": "000bx8mM3otnEd",
            "albumname": "冰伤",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 218,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 43004,
              "mid": "004T1lT91W9VVQ",
              "name": "谭嘉仪"
            }],
            "size128": 3504359,
            "size320": 8760614,
            "size5_1": 0,
            "sizeape": 20169543,
            "sizeflac": 20164826,
            "sizeogg": 4790342,
            "songid": 213187628,
            "songmid": "003hbmHM4FsHol",
            "songname": "冰伤",
            "songorig": "冰伤",
            "songtype": 0,
            "strMediaMid": "003RhsQh3F4S17",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "q0026q50fi6"
          },
          {
            "albumdesc": "",
            "albumid": 3938148,
            "albummid": "002PPv2T2PfmuE",
            "albumname": "周日司机",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 227,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 11735,
              "mid": "004LfgzR3pxV4q",
              "name": "洪卓立"
            }],
            "size128": 3643966,
            "size320": 9109618,
            "size5_1": 0,
            "sizeape": 49466595,
            "sizeflac": 49621096,
            "sizeogg": 5373141,
            "songid": 213228617,
            "songmid": "002erND13uzIOP",
            "songname": "周日司机",
            "songorig": "周日司机",
            "songtype": 0,
            "strMediaMid": "003DQdZ53nEgPr",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "j0026dtqm57"
          },
          {
            "albumdesc": "",
            "albumid": 3958587,
            "albummid": "001a14nJ3NvcDq",
            "albumname": "未来纪念馆",
            "alertid": 23,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 272,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 40049,
              "mid": "0030Rrxh1KLueM",
              "name": "Robynn & Kendy"
            }],
            "size128": 4353268,
            "size320": 10882822,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 6410351,
            "songid": 213356207,
            "songmid": "001UI1fO3xJZJX",
            "songname": "未来纪念馆",
            "songorig": "未来纪念馆",
            "songtype": 0,
            "strMediaMid": "001UI1fO3xJZJX",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3900765,
            "albummid": "000t3BvY48C8bm",
            "albumname": "一个独唱的理由",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 268,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1230237,
              "mid": "000sVXgL40Gf1W",
              "name": "潘伯仲"
            }],
            "size128": 4289307,
            "size320": 10722953,
            "size5_1": 0,
            "sizeape": 56451001,
            "sizeflac": 56741540,
            "sizeogg": 6228235,
            "songid": 213002409,
            "songmid": "003lCcXr3896SJ",
            "songname": "一个独唱的理由",
            "songorig": "一个独唱的理由",
            "songtype": 0,
            "strMediaMid": "002oztfA3xfLwO",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 4041474,
            "albummid": "001XIt5f0Wtu5v",
            "albumname": "The Makings Of",
            "alertid": 100002,
            "belongCD": 2,
            "cdIdx": 0,
            "interval": 252,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1021990,
              "mid": "00457ba60vPaMP",
              "name": "叶巧琳"
            }],
            "size128": 4039765,
            "size320": 10099128,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5947095,
            "songid": 213369900,
            "songmid": "000IjhqX1j1H4g",
            "songname": "残渣",
            "songorig": "残渣",
            "songtype": 0,
            "strMediaMid": "000IjhqX1j1H4g",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3881963,
            "albummid": "002PTCnV3QgttG",
            "albumname": "娱乐人生",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 233,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1612,
              "mid": "0017lQTg4BUMiK",
              "name": "陈蕾"
            }],
            "size128": 3742602,
            "size320": 9356212,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5483921,
            "songid": 212869239,
            "songmid": "000h4mzC3Fgaa5",
            "songname": "娱乐人生",
            "songorig": "娱乐人生",
            "songtype": 0,
            "strMediaMid": "000h4mzC3Fgaa5",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "o0025esa9gk"
          },
          {
            "albumdesc": "",
            "albumid": 1141352,
            "albummid": "001ELK3r4TgidW",
            "albumname": "最幸福的眼泪",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 252,
            "isonly": 1,
            "label": "5764607658334093314",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 62671,
              "tryend": 110219,
              "trysize": 761938
            },
            "rate": 0,
            "singer": [{
              "id": 6033,
              "mid": "002nWBET2t5iFx",
              "name": "吴雨霏"
            }],
            "size128": 4040617,
            "size320": 10101234,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5277325,
            "songid": 104176598,
            "songmid": "000fOfEg0CEZD4",
            "songname": "最幸福的眼泪",
            "songorig": "最幸福的眼泪",
            "songtype": 0,
            "strMediaMid": "000fOfEg0CEZD4",
            "stream": 2,
            "switch": 636675,
            "type": 0,
            "vid": "t0017bkgvhd"
          },
          {
            "albumdesc": "",
            "albumid": 3932096,
            "albummid": "004Mo0sV0LzTee",
            "albumname": "城市当代配乐团",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 231,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 13518,
              "mid": "003YvSXt2hntaP",
              "name": "RubberBand"
            }],
            "size128": 3699580,
            "size320": 9248616,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5120712,
            "songid": 213195707,
            "songmid": "003Esjl047dCKk",
            "songname": "城市当代配乐团",
            "songorig": "城市当代配乐团",
            "songtype": 0,
            "strMediaMid": "003Esjl047dCKk",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3935598,
            "albummid": "003HuaHc1oc001",
            "albumname": "老佛爷",
            "alertid": 100002,
            "belongCD": 12,
            "cdIdx": 0,
            "interval": 285,
            "isonly": 0,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1513762,
              "mid": "003MjN711OekmM",
              "name": "BAKERIE"
            }],
            "size128": 4569333,
            "size320": 11423028,
            "size5_1": 0,
            "sizeape": 57998582,
            "sizeflac": 57540253,
            "sizeogg": 6285993,
            "songid": 213213670,
            "songmid": "002i6jYH4VG6vn",
            "songname": "早班火车",
            "songorig": "早班火车",
            "songtype": 0,
            "strMediaMid": "002i6jYH4VG6vn",
            "stream": 8,
            "switch": 636675,
            "type": 0,
            "vid": "w0025pblypa"
          },
          {
            "albumdesc": "",
            "albumid": 3952688,
            "albummid": "003388tk1RJj3C",
            "albumname": "小明少少明",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 279,
            "isonly": 0,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 41879,
              "mid": "000pUqKx4Rh0fK",
              "name": "ToNick"
            }],
            "size128": 4479058,
            "size320": 11197334,
            "size5_1": 0,
            "sizeape": 32095494,
            "sizeflac": 32219768,
            "sizeogg": 5978474,
            "songid": 213323186,
            "songmid": "004IGRxi25lpUR",
            "songname": "小明少少明",
            "songorig": "小明少少明",
            "songtype": 0,
            "strMediaMid": "000Yoedm1sBeIi",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "n0026uq39fc"
          },
          {
            "albumdesc": "",
            "albumid": 3958078,
            "albummid": "004YgxoD0skj9T",
            "albumname": "其实我牵挂",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 261,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 968229,
              "mid": "000e7gbY0XOBNZ",
              "name": "谢文欣"
            }],
            "size128": 4187317,
            "size320": 10467842,
            "size5_1": 0,
            "sizeape": 27916461,
            "sizeflac": 28045369,
            "sizeogg": 5703718,
            "songid": 213353732,
            "songmid": "000bRnIN4b1IKu",
            "songname": "其实我牵挂",
            "songorig": "其实我牵挂",
            "songtype": 0,
            "strMediaMid": "000bRnIN4b1IKu",
            "stream": 8,
            "switch": 636675,
            "type": 0,
            "vid": "o00262du2x1"
          },
          {
            "albumdesc": "",
            "albumid": 3954854,
            "albummid": "003PpkPz09n85P",
            "albumname": "没有人是孤岛",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 247,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 947139,
              "mid": "003OwliN3eJZ5L",
              "name": "颜卓灵"
            }],
            "size128": 3961623,
            "size320": 9903749,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5331818,
            "songid": 213334168,
            "songmid": "003S7Oe51oVsug",
            "songname": "没有人是孤岛",
            "songorig": "没有人是孤岛",
            "songtype": 0,
            "strMediaMid": "003S7Oe51oVsug",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3959384,
            "albummid": "002hfiZ23ND8Vm",
            "albumname": "阶砖三",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 283,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 148,
              "mid": "0005pQip42flOb",
              "name": "吴浩康"
            }],
            "size128": 4532543,
            "size320": 11331067,
            "size5_1": 0,
            "sizeape": 56328745,
            "sizeflac": 56708670,
            "sizeogg": 6579902,
            "songid": 213360498,
            "songmid": "003wO2qW41hJbE",
            "songname": "阶砖三",
            "songorig": "阶砖三",
            "songtype": 0,
            "strMediaMid": "003tNPSh1Gj6wp",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "c00261gsn2z"
          },
          {
            "albumdesc": "",
            "albumid": 4043470,
            "albummid": "004cJL6H4LSfi3",
            "albumname": "偷听情歌",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 254,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 28688,
              "mid": "003PDwti3g1aa3",
              "name": "胡鸿钧"
            }],
            "size128": 4080733,
            "size320": 10201536,
            "size5_1": 0,
            "sizeape": 50874247,
            "sizeflac": 51287958,
            "sizeogg": 5450111,
            "songid": 213917220,
            "songmid": "001gKkfE37lSQb",
            "songname": "偷听情歌",
            "songorig": "偷听情歌",
            "songtype": 0,
            "strMediaMid": "001gKkfE37lSQb",
            "stream": 10,
            "switch": 636675,
            "type": 0,
            "vid": "n00263mlz9m"
          },
          {
            "albumdesc": "《黄金花》电影主题曲",
            "albumid": 3907550,
            "albummid": "003vRWuv1yg9Ic",
            "albumname": "黄金花",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 254,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 147,
              "mid": "002UyzMA2PZJd4",
              "name": "赵学而"
            }],
            "size128": 4073258,
            "size320": 10182776,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5476079,
            "songid": 213048993,
            "songmid": "001Tv9sl2oriAb",
            "songname": "黄金花",
            "songorig": "黄金花",
            "songtype": 0,
            "strMediaMid": "001Tv9sl2oriAb",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": "d0026g04uee"
          },
          {
            "albumdesc": "",
            "albumid": 3871306,
            "albummid": "004Wac873SHMJq",
            "albumname": "当下的力量",
            "alertid": 100002,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 299,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 110,
              "mid": "000GrAPo1lz8mZ",
              "name": "周国贤"
            }],
            "size128": 4797955,
            "size320": 11994585,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 7019115,
            "songid": 212808512,
            "songmid": "002WBPCx1evHRX",
            "songname": "当下的力量",
            "songorig": "当下的力量",
            "songtype": 0,
            "strMediaMid": "002WBPCx1evHRX",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3916890,
            "albummid": "002vmxfR1setMt",
            "albumname": "Evolution·演化",
            "alertid": 11,
            "belongCD": 2,
            "cdIdx": 0,
            "interval": 226,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 4918,
              "mid": "003s4LyG1MDky5",
              "name": "Soler"
            }],
            "size128": 3625592,
            "size320": 9063659,
            "size5_1": 0,
            "sizeape": 26259242,
            "sizeflac": 26391222,
            "sizeogg": 5148286,
            "songid": 213103005,
            "songmid": "000nzcnu3p24au",
            "songname": "重燃",
            "songorig": "重燃",
            "songtype": 0,
            "strMediaMid": "000nzcnu3p24au",
            "stream": 10,
            "switch": 606007,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3081658,
            "albummid": "001Drwnj2erRa1",
            "albumname": "I",
            "alertid": 100002,
            "belongCD": 8,
            "cdIdx": 0,
            "interval": 227,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 11436,
              "mid": "003Z6Uiu1dvLv0",
              "name": "陈柏宇"
            }],
            "size128": 3647727,
            "size320": 9119022,
            "size5_1": 0,
            "sizeape": 24356477,
            "sizeflac": 24461227,
            "sizeogg": 5239622,
            "songid": 202982655,
            "songmid": "0037RYUn2ct3Cs",
            "songname": "霸气情歌",
            "songorig": "霸气情歌",
            "songtype": 0,
            "strMediaMid": "0036rdux3u3ooZ",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3944379,
            "albummid": "0030KqeL04cevS",
            "albumname": "封箱",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 249,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1566922,
              "mid": "000VpcZT0qIJbP",
              "name": "徐加晴"
            }],
            "size128": 4000059,
            "size320": 9999863,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5473825,
            "songid": 213264993,
            "songmid": "001kFUDM1IBnsy",
            "songname": "封箱",
            "songorig": "封箱",
            "songtype": 0,
            "strMediaMid": "001kFUDM1IBnsy",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3911831,
            "albummid": "002S1sFs3odHVc",
            "albumname": "原来这就是爱情",
            "alertid": 100002,
            "belongCD": 3,
            "cdIdx": 0,
            "interval": 236,
            "isonly": 0,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1128957,
              "mid": "0037SGmd0JzRuc",
              "name": "The Bright Lights"
            }],
            "size128": 3786510,
            "size320": 9465948,
            "size5_1": 0,
            "sizeape": 54846471,
            "sizeflac": 54588209,
            "sizeogg": 5954697,
            "songid": 213076000,
            "songmid": "004MkM7f3kEqhJ",
            "songname": "原来这就是爱情",
            "songorig": "原来这就是爱情",
            "songtype": 0,
            "strMediaMid": "004MkM7f3kEqhJ",
            "stream": 10,
            "switch": 636675,
            "type": 0,
            "vid": "p0026txrkvm"
          },
          {
            "albumdesc": "",
            "albumid": 3983460,
            "albummid": "001UP8rJ2ef1tm",
            "albumname": "晚婚少女",
            "alertid": 11,
            "belongCD": 0,
            "cdIdx": 0,
            "interval": 195,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 1102361,
              "mid": "003DCUwh4DGeJL",
              "name": "何璟昕"
            }],
            "size128": 3134473,
            "size320": 7835887,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 3843634,
            "songid": 213524983,
            "songmid": "0040Fmp62nzcq8",
            "songname": "晚婚少女",
            "songorig": "晚婚少女",
            "songtype": 0,
            "strMediaMid": "0040Fmp62nzcq8",
            "stream": 0,
            "switch": 606007,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 3970170,
            "albummid": "000heLPi33iGXD",
            "albumname": "荒原",
            "alertid": 23,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 251,
            "isonly": 1,
            "label": "0",
            "msgid": 14,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 1,
              "payinfo": 1,
              "payplay": 0,
              "paytrackmouth": 1,
              "paytrackprice": 200,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 23303,
              "mid": "002vbAYi0xBan1",
              "name": "卢凯彤"
            }],
            "size128": 4021375,
            "size320": 10053153,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5497083,
            "songid": 213428823,
            "songmid": "001XvA8j2ulVCj",
            "songname": "荒原",
            "songorig": "荒原",
            "songtype": 0,
            "strMediaMid": "001XvA8j2ulVCj",
            "stream": 0,
            "switch": 636675,
            "type": 0,
            "vid": "z0026t3k55w"
          },
          {
            "albumdesc": "",
            "albumid": 3954990,
            "albummid": "001bsiHa0pOE5s",
            "albumname": "把持",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 205,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 946308,
              "mid": "00401gEH2mUbDQ",
              "name": "吴嘉熙"
            }],
            "size128": 3286185,
            "size320": 8215177,
            "size5_1": 0,
            "sizeape": 0,
            "sizeflac": 0,
            "sizeogg": 5025070,
            "songid": 213334930,
            "songmid": "002fPxdc2bFVt3",
            "songname": "把持",
            "songorig": "把持",
            "songtype": 0,
            "strMediaMid": "002fPxdc2bFVt3",
            "stream": 0,
            "switch": 81719,
            "type": 0,
            "vid": ""
          },
          {
            "albumdesc": "",
            "albumid": 4003589,
            "albummid": "000pSwyQ1QUNYv",
            "albumname": "苦情侠",
            "alertid": 11,
            "belongCD": 1,
            "cdIdx": 0,
            "interval": 244,
            "isonly": 0,
            "label": "0",
            "msgid": 0,
            "pay": {
              "payalbum": 0,
              "payalbumprice": 0,
              "paydownload": 0,
              "payinfo": 0,
              "payplay": 0,
              "paytrackmouth": 0,
              "paytrackprice": 0,
              "timefree": 0
            },
            "preview": {
              "trybegin": 0,
              "tryend": 0,
              "trysize": 0
            },
            "rate": 0,
            "singer": [{
              "id": 2138314,
              "mid": "000Pa2Pg4CeWh3",
              "name": "邓思朗"
            }],
            "size128": 3911456,
            "size320": 9778349,
            "size5_1": 0,
            "sizeape": 51767977,
            "sizeflac": 51827072,
            "sizeogg": 5647087,
            "songid": 213681410,
            "songmid": "000acnNx17tbh9",
            "songname": "苦情侠",
            "songorig": "苦情侠",
            "songtype": 0,
            "strMediaMid": "000acnNx17tbh9",
            "stream": 9,
            "switch": 606007,
            "type": 0,
            "vid": "d00265alc1q"
          }
        ],
        "visitnum": 1201817,
        "cmtnum": 0,
        "buynum": 0,
        "scoreavage": "0.0",
        "scoreusercount": 0
      }]
    },
    actions,
    mutations,
    getters
  })
}

